services:
  audio-transcriber-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${DOCKER_PORT:-8000}
    container_name: audio-transcriber-api
    ports:
      - "${DOCKER_PORT:-8000}:${DOCKER_PORT:-8000}"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE_MB=25
    volumes:
      # Volume for logs (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DOCKER_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx for reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: audio-transcriber-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - audio-transcriber-api
    profiles:
      - production

volumes:
  logs:
